[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_APPWRITE_PROJECT_ID,NEXT_PUBLIC_DATABASE_ID,NEXT_PUBLIC_APPWRITE_ENDPOINT"
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"
