export const LITERALS = {
    COMMON: {
        CANCEL: "Cancelar",
        CONFIRM: "Confirmar",
        UNDERSTOOD: "Entendido",
        LOGOUT: "Cerrar Sesión",
        LOADING: "Cargando...",
        ERROR: "Error",
        SUCCESS: "Éxito",
        WARNING: "Aviso",
        INFO: "Información",
        SAVE: "Guardar",
        DELETE: "Borrar",
        EDIT: "Editar",
        BACK: "Atrás",
        TODAY: "Hoy",
        TOMORROW: "Mañana",
        YESTERDAY: "Ayer",
    },
    NAVBAR: {
        MY_PROFILE: "Mi Perfil",
        BOOKINGS: "Reservas",
        CONTROL_PANEL: "Panel de Control",
        ACCOUNTING: "Contabilidad",
        RESERVE_BUTTON: "Reservar",
        USER_DEFAULT: "Usuario",
    },
    CLASS_GRID: {
        TITLE: "Clases Disponibles",
    },
    DASHBOARD: {
        TITLE: "Panel de Control",
        STUDENTS_DIRECTORY: "Directorio de Alumnos",
        ACTIVE_STUDENTS: "Alumnos Activos",
        TOTAL_STUDENTS: "Alumnos totales",
        MONTHLY_REVENUE: (month: string) => `Ingresos ${month}`,
        PENDING_PAYMENT: "Pendientes de pago",
        ALL_UP_TO_DATE: "Todo al día",
        SEARCH_PLACEHOLDER: "Buscar alumno o email...",
        FILTER_ALL_PAYMENTS: "Todos los Pagos",
        FILTER_PAID: "Pagados",
        FILTER_PENDING: "Pendientes",
        FILTER_ALL_LEVELS: "Todos los Niveles",
        CLEAN_FILTERS: "Limpiar Filtros",
        LOAD_MORE_STUDENTS: (count: number) => `Cargar más alumnos (${count} restantes)`,

        TABS: {
            GENERAL: "General",
            ANNOUNCEMENTS: "Tablón",
            CLASSES: "Clases y Horarios",
        },

        ANNOUNCEMENTS: {
            CREATE_TITLE: "Crear Anuncio",
            PANEL_TITLE: "Tablón de Anuncios",
            DESCRIPTION: "Notifica a todos los alumnos.",
            INPUT_TITLE: "Título",
            INPUT_CONTENT: "Mensaje",
            INPUT_IMPORTANCE: "Importancia",
            PLACEHOLDER_TITLE: "Ej: Festivo el Lunes",
            PLACEHOLDER_CONTENT: "Escribe el aviso aquí...",
            PUBLISH_BUTTON: "Publicar Anuncio",
            EMPTY_STATE: "No hay anuncios recientes.",
            MARK_ALL_READ: "Marcar todo como leído",
        },

        CLASSES: {
            TITLE: "Horarios y Clases",
            DESCRIPTION: "Programa las próximas sesiones para que los alumnos puedan reservar.",
            AUTO_GENERATE: "Auto-Siguiente Semana",
            SCHEDULE_BUTTON: "+ Programar Clase",
            HISTORY_TITLE: "Historial Reciente",
            HISTORY_DESCRIPTION: "Clases que han ocurrido en las últimas 48 horas.",
        },
        ACCOUNTING: {
            TITLE: "Contabilidad Central",
            SUBTITLE: "Control de ingresos mensuales y salud financiera.",
            GO_BACK: "Volver al Panel",
            SELECT_YEAR: "Seleccionar Año",
            SELECT_MONTH: "Seleccionar Mes",
            TOTAL_REVENUE: "Ingresos Totales",
            NO_DATA: "Sin datos para este periodo",
            TABS: {
                MONTHLY: "Balance Mensual",
            }
        }
    },
    BOOKINGS: {
        TITLE: "Reservas",
        SUBTITLE: "Selecciona tu próxima sesión en el tatami.",
        MY_RESERVATIONS: "Mis Reservas",
        AVAILABLE_CLASSES: "Clases Disponibles",
        SHOWING_AVAILABILITY: "Disponibilidad los proximos 7 días",
        EMPTY_STATE: "No hay plazas nuevas disponibles para reservar en este momento.",
        CONFIRM_RESERVATION_TITLE: "Confirmar Reserva",
        CONFIRM_RESERVATION_DESC: (date: string, time: string) => `¿Quieres reservar tu plaza para la clase del ${date} a las ${time}?`,
        CANCEL_RESERVATION_TITLE: "Cancelar Reserva",
        CANCEL_RESERVATION_DESC: (date: string, time: string) => `¿Seguro que quieres cancelar tu plaza para la clase del ${date} a las ${time}? Esta acción permitirá que otro compañero asista.`,
    },
    CLASS_CARD: {
        FREE_SPACES: (count: number) => `${count} plazas libres`,
        FULL: "Completa",
        TOTAL_CAPACITY: (total: number) => `${total} TOTAL`,
        RESERVE_BUTTON: "Reservar Mi Sitio",
        PENDING_PAYMENT: "⚠️ Pago Pendiente",
        NO_SPACES: "Sin Plazas",
        VIEW_ATTENDEES: "Ver Listado",
        CANCEL_CLASS: "Cancelar Clase",
        DANGER_BADGE: "Peligro",
        PAST_CLASS_INFO: "No hay acciones disponibles para clases pasadas",
        LOAD_MORE: (date: string) => `Ver ${date}`,
        LOAD_MORE_HISTORY: (date: string) => `Ver ${date}`,
        HISTORY_EMPTY_STATE: "No hay historial reciente de clases registradas.",
        HISTORY_EMPTY_SUB: "Las clases aparecerán aquí una vez hayan finalizado.",
        EMPTY_SUB: "Vuelve a consultar más tarde para nuevas sesiones.",
        START_TIME: "Comienzo",
    }
};
